version: "3.3"
services:
  
  users:
    build: ./users
    container_name: users
    image: ghcr.io/arquisoft/yovi_es1a-users:latest
    environment:
      - RUST_API_URL=http://gamey:4000
    networks:
      - monitor-net
    env_file:
      - ./users/.env

  webapp:
    build:
      context: ./webapp
      args:
<<<<<<< HEAD
        - VITE_API_URL=http://localhost:3000
        - VITE_API_ENDPOINT=http://localhost:4000
        - VITE_MULTIPLAYER_URL=http://localhost:5000
=======
        - VITE_API_URL=/api
        - VITE_API_ENDPOINT=/api/gamey
        - VITE_MULTIPLAYER_URL=/
>>>>>>> origin/https
    container_name: webapp
    image: ghcr.io/arquisoft/yovi_es1a-webapp:latest
    depends_on:
      - users
    networks:
      - monitor-net

  gamey:
    build: ./gamey
    container_name: gamey
    image: ghcr.io/arquisoft/yovi_es1a-gamey:latest
    networks:
      - monitor-net
  multiplayer:
    build: 
      context: ./multiplayer
    networks:        
      - monitor-net 
    environment:
      - PORT=5000
    restart: unless-stopped
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./users/monitoring/prometheus:/etc/prometheus
    networks:
      - monitor-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/cert.pem:/etc/nginx/certs/cert.pem:ro
      - ./certs/key.pem:/etc/nginx/certs/key.pem:ro
    depends_on:     
      - gamey       
      - users       
      - webapp       
      - multiplayer 
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9091:3000"
    volumes:
      - ./users/monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge
volumes:
  mongodb-data: