events { worker_connections 1024; }

http {
    # 1. Force HTTPS
    server {
        listen 80;
        server_name localhost 127.0.0.1 20.199.88.71; 
        return 301 https://$host$request_uri;
    }

    # 2. The main secure server
    server {
        listen 443 ssl;
        server_name localhost 127.0.0.1 20.199.88.71;

        ssl_certificate /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        # A: Rust API (gamey)
        location /api/gamey/ {
            proxy_pass http://gamey:4000/; 
            proxy_set_header Host $host;
        }
        
        # El motor de Bots
        location /api/bot/ {
            proxy_pass http://users:3000/api/bot/; 
            proxy_set_header Host $host;
        }

        location /api/matches/ {
            proxy_pass http://users:3000/matches/; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        # CLanes
        location /api/clans/ {
            proxy_pass http://users:3000/clans/; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # B: Node User API
        location /api/ {
            proxy_pass http://users:3000/; 
            proxy_set_header Host $host;
        }

        location /api-docs {
            proxy_pass http://users:3000/api-docs;
        }

        # C: Sockets for multiplayer (Socket.IO)
        location /socket.io/ {
            proxy_pass http://multiplayer:5000/socket.io/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }

        # D: The Vite/React Frontend
        location / {
            proxy_pass http://webapp:80; 
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
    }
}