sonar.organization=arquisoft
sonar.host.url=https://sonarcloud.io
sonar.projectKey=Arquisoft_yovi_es1a
sonar.projectName=yovi_es1a

sonar.sources=webapp/src,users,gamey/src,multiplayer/src
sonar.tests=webapp/src,users/__tests__,gamey/src,multiplayer/src
sonar.test.inclusions=**/*.test.tsx,**/*.test.js
sonar.javascript.lcov.reportPaths=webapp/coverage/lcov.info,users/coverage/lcov.info,multiplayer/coverage/lcov.info
sonar.rust.lcov.reportPaths=gamey/lcov.info
sonar.exclusions=**/*.test.tsx,**/*.test.ts,**/*.test.js,**/*.spec.ts, \
                 webapp/src/main.tsx, \
                 webapp/src/App.tsx, \
                 webapp/src/env.d.ts, \
                 webapp/src/Routes.tsx, \
                 webapp/src/pages/About.tsx, \
                 webapp/src/pages/Help.tsx, \
                 webapp/src/pages/Home.tsx, \
                 webapp/src/components/BotTester.tsx, \
                 webapp/src/services/socket.service.ts, \
                 webapp/src/services/api.ts, \
                 webapp/src/context/**, \
                 webapp/src/recursos/**
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts,**/*.test.js,**/*.spec.ts