ifndef::imagesdir[:imagesdir: ../images]

[[section-context-and-scope]]
== Context and Scope


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Context and scope - as the name suggests - delimits your system (i.e. your scope) from all its communication partners
(neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).

.Motivation
The domain interfaces and technical interfaces to communication partners are among your system's most critical aspects. Make sure that you completely understand them.

.Form
Various options:

* Context diagrams
* Lists of communication partners and their interfaces.


.Further Information

See https://docs.arc42.org/section-3/[Context and Scope] in the arc42 documentation.

****
endif::arc42help[]

=== Business Context

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Specification of *all* communication partners (users, IT-systems, ...) with explanations of domain specific inputs and outputs or interfaces.
Optionally you can add domain specific formats or communication protocols.

.Motivation
All stakeholders should understand which data are exchanged with the environment of the system.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.

****
endif::arc42help[]

[plantuml, business-context-diagram, png]
----
@startuml
skinparam componentStyle uml2
skinparam backgroundColor white

left to right direction

actor "User" as user
component "Yovi" as yovi
component "Monitoring System\n(Prometheus/Grafana)" as monitor

user --> yovi

yovi <-- monitor

@enduml
----

Diagram elements:

- User: Represents the player or client who actively interacts with the system to use its functionalities.

- Yovi: It is the core of the system (the scope of this project). It acts as a central intermediary managing the business logic.

- Monitoring System (Prometheus/Grafana): This is the external component responsible for observability. It does not participate in the game, but audits the technical status of the system.

=== Technical Context

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation which I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****
endif::arc42help[]


[plantuml, technical-context-diagram, png]
----
@startuml
skinparam componentStyle uml2
skinparam backgroundColor white
left to right direction

actor "User" as dev

node "Client" {
    component "Terminal (User agent)" as client
}

node "Docker Host (Localhost)" {
    
    package "monitor-net (Docker Network)" {
        component "Users Service" as users
        component "Gamey Service" as gamey
        
        component "Prometheus" as prom
        component "Grafana" as graf
    }
}


dev --> client : Executes Commands (manual input)

client --> users : Sends API Requests\n[HTTP/JSON :3000]
client --> gamey : Sends API Requests\n[HTTP/JSON :4000]
client --> graf : Accesses Dashboard\n[HTTP/Web :9091]

graf --> prom : Queries Data\n[HTTP API :9090]
prom --> users : Scrapes Metrics\n[HTTP GET :3000]

@enduml
----

The Yovi system uses a set of HTTP interfaces for communication between microservices and for exposing data to the client. The communication channels represented in the architecture diagram are detailed below:
1. External access interfaces:
    - User management and game logic API: The HTTP client interacts with the Users Service (port 3000) and the Gamey Service (port 4000) by sending and receiving data exclusively in JSON format. These interfaces manage authentication and game mechanics using the HTTP protocol, without including visual elements.
    - Visualization interface: This connection delivers the Grafana graphical interface to the client via port 9091. It uses the HTTP (Web) standard to serve the necessary HTML and CSS code that allows the administrator to view the control panels.
2. Internal interfaces:
    - Collection and query channel within the private network: Prometheus makes periodic HTTP GET requests to the Users Service's internal port 3000 to collect technical health metrics. Simultaneously, Grafana queries the Prometheus database on port 9090 to retrieve historical data and generate graphs.
3. Control Interfaces:
    - Command Input: The user uses the terminal as a manual control interface. By executing commands, they make requests to the system to simulate user behavior and verify the functionality of the services.
